model_opts:
  model: BaseTransformer
  obs_input_type: [box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: False
  reshape_input_to_1d_list: True
net_opts:
  num_hidden_units: 128
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg16
exp_opts:
  datasets: [jaad_beh]
  batch_size: [32, 32, 32]
  epochs: [100, 100, 100]
  lr: [0.0001, 0.0001, 0.0001]
