model_opts:
  model: MultiRNN
  obs_input_type: [box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg16
exp_opts:
  datasets: [jaad_beh]
  batch_size: [32, 32, 32]
  epochs: [40, 40, 40]
  lr: [0.0000001, 0.0000001, 0.0000001]
